# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gBoxModeSelector = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gBoxModeSelector.setFont(font)
        self.gBoxModeSelector.setAlignment(QtCore.Qt.AlignCenter)
        self.gBoxModeSelector.setFlat(False)
        self.gBoxModeSelector.setObjectName("gBoxModeSelector")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gBoxModeSelector)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.butVisualize = QtWidgets.QToolButton(self.gBoxModeSelector)
        self.butVisualize.setMinimumSize(QtCore.QSize(100, 80))
        self.butVisualize.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.butVisualize.setFont(font)
        self.butVisualize.setCheckable(True)
        self.butVisualize.setChecked(True)
        self.butVisualize.setAutoExclusive(True)
        self.butVisualize.setObjectName("butVisualize")
        self.verticalLayout_2.addWidget(self.butVisualize)
        self.butTracking = QtWidgets.QToolButton(self.gBoxModeSelector)
        self.butTracking.setMinimumSize(QtCore.QSize(100, 80))
        self.butTracking.setMaximumSize(QtCore.QSize(100, 100))
        self.butTracking.setCheckable(True)
        self.butTracking.setAutoExclusive(True)
        self.butTracking.setObjectName("butTracking")
        self.verticalLayout_2.addWidget(self.butTracking)
        self.butAnalysis = QtWidgets.QToolButton(self.gBoxModeSelector)
        self.butAnalysis.setMinimumSize(QtCore.QSize(100, 80))
        self.butAnalysis.setMaximumSize(QtCore.QSize(100, 100))
        self.butAnalysis.setCheckable(True)
        self.butAnalysis.setAutoExclusive(True)
        self.butAnalysis.setObjectName("butAnalysis")
        self.verticalLayout_2.addWidget(self.butAnalysis)
        self.textEdit = QtWidgets.QTextEdit(self.gBoxModeSelector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.gBoxModeSelector)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.page)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.widget)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.butPlay = QtWidgets.QPushButton(self.groupBox_2)
        self.butPlay.setCheckable(True)
        self.butPlay.setObjectName("butPlay")
        self.horizontalLayout_3.addWidget(self.butPlay)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.labelTimestamp = QtWidgets.QLabel(self.groupBox_2)
        self.labelTimestamp.setObjectName("labelTimestamp")
        self.horizontalLayout_3.addWidget(self.labelTimestamp)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(4, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenTraj"))
        self.gBoxModeSelector.setTitle(_translate("MainWindow", "Mode"))
        self.butVisualize.setToolTip(_translate("MainWindow", "Visualize tooltip"))
        self.butVisualize.setText(_translate("MainWindow", "Visualize"))
        self.butTracking.setToolTip(_translate("MainWindow", "Tracking tooltip"))
        self.butTracking.setText(_translate("MainWindow", "Tracking"))
        self.butAnalysis.setToolTip(_translate("MainWindow", "Analysis tooltip"))
        self.butAnalysis.setText(_translate("MainWindow", "Analysis"))
        self.butPlay.setText(_translate("MainWindow", "Play | Pause"))
        self.labelTimestamp.setText(_translate("MainWindow", "0"))
